In [1]:
    import numpy as np
    import matplotlib.pyplot as plt
    import statistics as st
    import seaborn as sns
    import pandas as pd
    from pandas import DataFrame, Series
    %matplotlib inline

# Checking out the databases

In [2]:
batting = pd.read_csv('Batting.csv')

In [3]:
batting.SF = batting.SF.fillna(0)

In [4]:
salary=pd.read_csv('Salaries.csv', index_col = 'playerID', usecols=[3,4])

In [5]:
salary=salary[salary !=0]

In [6]:
appearances = pd.read_csv('Appearances.csv')

In [7]:
batting=pd.read_csv('Batting.csv', index_col = 'playerID', usecols=[0,1,6,7,8,9,10,11,12,15,18,20])

In [8]:
field=pd.read_csv('Fielding.csv', index_col = 'playerID', usecols=[0,1,5])

# Create OBP

In [9]:
batting['OBP'] = (batting['H']+batting['BB']+batting['HBP'])/(batting['AB']+batting['BB']+batting['HBP']+batting['SF'])

# Merging the databases

In [10]:
master=pd.read_csv('Master.csv', index_col = 'playerID', usecols=[0,13,14])

In [11]:
master_merge = master.merge(field, how='outer',left_index=True, right_index=True)

In [12]:
master_merge2 = master_merge.merge(salary, how='outer',left_index=True, right_index=True)

In [13]:
master_merge3 = master_merge2.merge(batting[['OBP']], left_index=True, right_index=True)

In [20]:
master_merge3.sort_values(['salary', 'OBP'], ascending=[True, False]).head(10000)

          nameFirst     nameLast  yearID POS   salary       OBP
playerID
musseje01      Jeff    Musselman  1986.0   P  60000.0  1.000000
olwined01        Ed       Olwine  1986.0   P  60000.0  0.500000
tillmru01     Rusty      Tillman  1982.0  OF  60000.0  0.500000
danieka01       Kal      Daniels  1986.0  OF  60000.0  0.389535
mitchke01     Kevin     Mitchell  1984.0  3B  60000.0  0.387500
brownch02     Chris        Brown  1984.0  3B  60000.0  0.357895
aldremi01      Mike      Aldrete  1986.0  1B  60000.0  0.357143
willire01    Reggie     Williams  1985.0  LF  60000.0  0.333333
hearned02        Ed        Hearn  1986.0   C  60000.0  0.322148
quinore01       Rey     Quinones  1986.0  SS  60000.0  0.314554
grosswa01     Wayne        Gross  1976.0  RF  60000.0  0.310526
lakest01      Steve         Lake  1983.0   C  60000.0  0.303571
trabeji01       Jim       Traber  1984.0  DH  60000.0  0.291667
mullifr01      Fran      Mullins  1980.0  3B  60000.0  0.291667
guilloz01     Ozzie      Guillen  1985.0  SS  60000.0  0.291089
kutchra01     Randy      Kutcher  1986.0  2B  60000.0  0.279188
mizerjo01      John     Mizerock  1983.0   C  60000.0  0.262626
speckcl01     Cliff        Speck  1986.0   P  60000.0  0.250000
martimi01      Mike       Martin  1986.0   C  60000.0  0.200000
maddumi01      Mike       Maddux  1986.0   P  60000.0  0.166667
mathegr01      Greg      Mathews  1986.0   P  60000.0  0.088889
soffra01        Ray         Soff  1986.0   P  60000.0  0.000000
anderla02     Larry     Andersen  1975.0   P  60000.0  0.000000
moonebi01      Bill    Mooneyham  1986.0   P  60000.0       NaN
loyndmi01      Mike        Loynd  1986.0   P  60000.0       NaN
bailesc01     Scott       Bailes  1986.0   P  60000.0       NaN
kinger01       Eric         King  1986.0   P  60000.0       NaN
mckeojo01      Joel       McKeon  1986.0   P  60000.0       NaN
cluttbr01     Bryan  Clutterbuck  1986.0   P  60000.0       NaN
holtobr01     Brian       Holton  1985.0   P  60000.0       NaN
...             ...          ...     ...  ..      ...       ...
klinero01       Ron        Kline  1952.0   P      NaN       NaN
clarkbu01      Buzz     Clarkson  1952.0  SS      NaN       NaN
tiefebo01     Bobby   Tiefenauer  1952.0   P      NaN       NaN
blackjo02       Joe        Black  1952.0   P      NaN       NaN
bradsge01    George     Bradshaw  1952.0   C      NaN       NaN
grossha01    Harley     Grossman  1952.0   P      NaN       NaN
kellnwa01      Walt      Kellner  1952.0   P      NaN       NaN
kellsk01    Skeeter         Kell  1952.0  2B      NaN       NaN
hamilto01       Tom     Hamilton  1952.0  1B      NaN       NaN
millest01       Stu       Miller  1952.0   P      NaN       NaN
yuhased01     Eddie        Yuhas  1952.0   P      NaN       NaN
schmege01    George      Schmees  1952.0  1B      NaN       NaN
thomaki01      Kite       Thomas  1952.0  OF      NaN       NaN
whisepe01      Pete    Whisenant  1952.0  OF      NaN       NaN
delgrbo01     Bobby    Del Greco  1952.0  OF      NaN       NaN
clarkmi01      Mike        Clark  1952.0   P      NaN       NaN
fussele01       Les    Fusselman  1952.0   C      NaN       NaN
mahonbo01       Bob      Mahoney  1951.0   P      NaN       NaN
paineph01      Phil        Paine  1951.0   P      NaN       NaN
bokeldi01      Dick    Bokelmann  1951.0   P      NaN       NaN
turlebo01       Bob       Turley  1951.0   P      NaN       NaN
campofr01     Frank       Campos  1951.0  OF      NaN       NaN
marshfr01      Fred        Marsh  1951.0  SS      NaN       NaN
brownha01       Hal        Brown  1951.0   P      NaN       NaN
richtal01        Al      Richter  1951.0  SS      NaN       NaN
schalar01       Art    Schallock  1951.0   P      NaN       NaN
koskibi01      Bill        Koski  1951.0   P      NaN       NaN
sackafr01     Frank        Sacka  1951.0   C      NaN       NaN
youngdi01      Dick        Young  1951.0  2B      NaN       NaN
dempsco01       Con      Dempsey  1951.0   P      NaN       NaN

[10000 rows x 6 columns]

# Filter for year and POS

In [21]:
master_merge3 = master_merge3.sort_values(['yearID'], ascending=False)

In [16]:
master_merge3=master_merge3.drop_duplicates(subset=['nameFirst', 'nameLast'], keep='last')

In [17]:
def get_player(master_merge3):
    positions = ['1B','2B','3B','P','CF','SS','LF','RF','C']
    best_players = {}
    for position in positions:
        filtered_positions = master_merge3[master_merge3['POS'] == position]
        sorted_positions = filtered_positions.sort_values('OBP', ascending=False)
        top_players = sorted_positions[:3]
        best_players[position] = top_players
    return best_players

In [18]:
best_players = get_player(master_merge3)

In [19]:
best_players

{'1B':           nameFirst  nameLast  yearID POS    salary       OBP
 playerID
 souchst01       Bud  Souchock  1946.0  1B       NaN  1.000000
 youngke01     Kevin     Young  1992.0  1B  109000.0  0.666667
 nagelru01      Russ  Nagelson  1969.0  1B       NaN  0.600000,
 '2B':           nameFirst  nameLast  yearID POS  salary       OBP
 playerID
 popovpa01      Paul  Popovich  1966.0  2B     NaN  1.000000
 brettry01      Ryan     Brett  2015.0  2B     NaN  0.750000
 kuipedu01     Duane    Kuiper  1974.0  2B     NaN  0.666667,
 '3B':           nameFirst nameLast  yearID POS    salary       OBP
 playerID
 smithdi01      Dick    Smith  1951.0  3B       NaN  1.000000
 quinlto01       Tom  Quinlan  1990.0  3B  125000.0  0.666667
 millake01     Kevin   Millar  1998.0  3B  170000.0  0.666667,
 'C':           nameFirst nameLast  yearID POS  salary  OBP
 playerID
 streuwa01      Walt  Streuli  1954.0   C     NaN  1.0
 davisdo01      Doug    Davis  1988.0   C     NaN  1.0
 burkma01       Mack     Burk  1956.0   C     NaN  1.0,
 'CF':           nameFirst     nameLast  yearID POS  salary       OBP
 playerID
 wiedeto01       Tom  Wiedenbauer  1979.0  CF     NaN  0.666667
 duranlu01      Luis      Durango  2009.0  CF     NaN  0.615385
 hicksjo01       Joe        Hicks  1959.0  CF     NaN  0.500000,
 'LF':           nameFirst   nameLast  yearID POS    salary       OBP
 playerID
 nymanny01      Nyls      Nyman  1974.0  LF       NaN  0.666667
 colanmi01      Mike  Colangelo  1999.0  LF  200000.0  0.666667
 fordcu01       Curt       Ford  1985.0  LF   70000.0  0.625000,
 'P':            nameFirst nameLast  yearID POS     salary  OBP
 playerID
 igawake01        Kei    Igawa  2007.0   P  4000000.0  1.0
 lollati01        Tim   Lollar  1980.0   P   463000.0  1.0
 aumonph01  Phillippe   Aumont  2012.0   P   500000.0  1.0,
 'RF':           nameFirst   nameLast  yearID POS    salary       OBP
 playerID
 bernhju01      Juan  Bernhardt  1976.0  RF       NaN  1.000000
 mccarda01      Dave    McCarty  1993.0  RF  550000.0  0.666667
 whiteed01        Ed      White  1955.0  RF       NaN  0.600000,
 'SS':           nameFirst nameLast  yearID POS    salary       OBP
 playerID
 belloro01       Rob  Belloir  1975.0  SS       NaN  1.000000
 burriem01  Emmanuel  Burriss  2008.0  SS  625000.0  0.800000
 johnske04     Keith  Johnson  2000.0  SS       NaN  0.666667}